[project]
name = "asyncord"
version = "0.5.0"
description = "A smart and powerful base for creating discord bots and interaction with the API."
authors = [
    { name = "Vadim Suharnikov", email = "vsuharnikov@gmail.com" },
]
urls = { homepage = "https://github.com/suharnikov/asyncord", repository = "https://github.com/suharnikov/asyncord" }

dependencies = [
    "aiohttp>=3.8.1",
    "yarl>=1.8.1",
    "pydantic>=1.9.1",
    "sentinel>=1.0.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.2",
    "wemake-python-styleguide>=0.16.1",
    "autopep8>=1.6.0",
    "flake8>=4.0.1",
    "pytest-asyncio>=0.19.0",
]

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "-ra"
asyncio_mode = "auto"
testpaths = [
    "tests",
]
