[project]
name = "asyncord"
version = "0.5.0"
description = "A smart and powerful base for creating discord bots and interaction with the API."
authors = [
    { name = "Vadim Suharnikov", email = "vsuharnikov@gmail.com" },
]
urls = { homepage = "https://github.com/suharnikov/asyncord", repository = "https://github.com/suharnikov/asyncord" }

dependencies = [
    "aiohttp>=3.8.1",
    "yarl>=1.8.1",
    "pydantic>=1.9.1",
    "sentinel>=1.0.0",
    "loguru>=0.6.0",
    "rich>=12.5.1",
]
requires-python = ">=3.11.0"
readme = "README.md"
license = { text = "MIT" }
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.3.1",
    "wemake-python-styleguide>=0.17.0",
    "autopep8<1.7.0",                   # confglct with wemake-python-styleguide
    "flake8>=4.0.1",
    "pytest-asyncio>=0.19.0",
    "isort>=5.10.1",
]

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.isort]
line_length = 110
multi_line_output = 3
include_trailing_comma = true
length_sort = true

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "-ra"
asyncio_mode = "auto"
testpaths = [
    "tests",
]
