[project]
name = "help-desk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = ["asyncord", "python-dotenv>=1.0.1"]


[tool.uv.sources]
asyncord = { workspace = true }
