name: Release asyncord

on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  run-tests:
    uses: vadim-su/asyncord/.github/workflows/tests.yml@main

  publish:
    runs-on: ubuntu-latest
    needs: run-tests

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build package distributions
        run: uv build

      - name: Publish package distributions to PyPI
        run: uv publish
